/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ffe_core_FFEExec */

#ifndef _Included_ffe_core_FFEExec
#define _Included_ffe_core_FFEExec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ffe_core_FFEExec
 * Method:    nativeExec
 * Signature: (Ljava/lang/String;Ljava/lang/String;
               Ljava/lang/String;Ljava/lang/String;
               Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ffe_core_FFEExec_nativeExec
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
